services:
  postgres:
    image: albertzry/spinodyne-postgres:v0.1.0-beta.1

  redis:
    image: albertzry/spinodyne-redis:v0.1.0-beta.1

  minio:
    image: albertzry/spinodyne-minio:v0.1.0-beta.1

  backend:
    image: albertzry/spinodyne-backend:v0.1.0-beta.1
    build: null

  celery_worker:
    image: albertzry/spinodyne-backend:v0.1.0-beta.1

  frontend:
    image: albertzry/spinodyne-frontend:v0.1.0-beta.1
    build: null
